dist: xenial
services:
- mysql
language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- cd trabajoAII
- cp travis_local_settings.py local_settings.py
- cd ..
- python ./manage.py test
notifications:
  email:
    recipients:
      - javiersgjavi@gmail.com
    on_success: never # default: change
    on_failure: always # default: always