# Generated by Django 3.1.2 on 2020-12-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HOLa',
        ),
    ]
