# Generated by Django 3.1.2 on 2020-12-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
