# Generated by Django 3.1.2 on 2020-12-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_game', '0003_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
