# Generated by Django 3.1.2 on 2020-12-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_game', '0004_auto_20201229_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
