# Generated by Django 3.1.2 on 2021-01-09 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugadores', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='juego',
            name='jugadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.jugadores'),
        ),
    ]
