# Generated by Django 3.1.2 on 2021-01-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210109_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='desarrollador',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='generos',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='jugadores',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='plataformas',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='puntuaciones',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Desarrollador',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
        migrations.DeleteModel(
            name='Jugadores',
        ),
        migrations.DeleteModel(
            name='Plataforma',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
    ]
